# Generated by Django 3.2.13 on 2022-05-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
