# Generated by Django 3.2.13 on 2022-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0002_tournament_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='featured',
        ),
        migrations.AddField(
            model_name='tournament',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize2',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize3',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.CharField(default='', max_length=30),
        ),
    ]
