# Generated by Django 3.2.13 on 2022-05-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0003_auto_20220522_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
