# Generated by Django 3.2.13 on 2022-05-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0004_alter_tournament_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
