# Generated by Django 3.2.13 on 2022-05-31 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0007_auto_20220524_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='entryleft',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize1',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize2',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize3',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_pool',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='team_size',
            field=models.PositiveIntegerField(default=1, max_length=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
