# Generated by Django 3.2.13 on 2022-06-02 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0009_auto_20220601_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='last_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/'),
        ),
    ]
