# Generated by Django 3.2.13 on 2022-05-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='product',
            new_name='Tournament',
        ),
    ]
