# Generated by Django 3.2.13 on 2022-05-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerations', '0003_register_ign'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='entryleft_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('00', 'Registered'), ('01', 'Not Registered')], default='01', max_length=20),
        ),
    ]
